name: phpunit

on:
  push:
    branches: ['1.x']
  pull_request:
    branches: ['1.x']

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.0']

    name: P${{ matrix.php }}

    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
      with:
        php-version: ${{ matrix.php }}

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
      with:
        path: vendor
        key: ${{ runner.os }}-${{ matrix.php }}-node-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.php }}-node-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --no-progress --no-suggest

    - name: Run test suite
      run: vendor/bin/phpunit
